// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbrYwQIex0GR24FiDuUgI3KhfEvApDBuo',
    appId: '1:251374455602:web:80f5c46ef103f97475652b',
    messagingSenderId: '251374455602',
    projectId: 'ecom-firestore',
    authDomain: 'ecom-firestore.firebaseapp.com',
    storageBucket: 'ecom-firestore.appspot.com',
    measurementId: 'G-0599Y4LQJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBklnZ2Uq-J4vZ4e4g3QeejKPUPFpabbu8',
    appId: '1:251374455602:android:d9a5599e4da3155d75652b',
    messagingSenderId: '251374455602',
    projectId: 'ecom-firestore',
    storageBucket: 'ecom-firestore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0KjiDLMUKmUttt-NwDOV5JpsgUe9uvc',
    appId: '1:251374455602:ios:b5954b96cd4b7cc575652b',
    messagingSenderId: '251374455602',
    projectId: 'ecom-firestore',
    storageBucket: 'ecom-firestore.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0KjiDLMUKmUttt-NwDOV5JpsgUe9uvc',
    appId: '1:251374455602:ios:71beee8157e4382075652b',
    messagingSenderId: '251374455602',
    projectId: 'ecom-firestore',
    storageBucket: 'ecom-firestore.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
